FROM registry.redhat.io/ubi9/python-311@sha256:9bf5a438d4b62816655989ad336def43fb8c95de128e7afe2d455c1e38a0b233

WORKDIR /app

USER root
RUN curl -LsSf https://astral.sh/uv/install.sh | env UV_INSTALL_DIR=/usr/local/bin sh

COPY pyproject.toml __init__.py ./
COPY components/ components/
COPY pipelines/ pipelines/
COPY scripts/ scripts/
COPY utils/ utils/

RUN chown -R 1001:1001 /app
USER 1001

RUN uv sync --no-cache --extra test

RUN uv run python -m scripts.generate_managed_pipelines.generate_managed_pipelines

CMD [".venv/bin/python", "-m", "scripts.init_managed_pipelines.init_managed_pipelines"]