# This container is used to run the AutoRAG components of the training pipeline.

ARG BASE_IMAGE="quay.io/aipcc/base-images/cpu:3.4"

FROM ${BASE_IMAGE}

COPY pipelines/training/autorag/documents_rag_optimization_pipeline/requirements.txt \
     pipelines/training/autorag/documents_rag_optimization_pipeline/requirements-pypi.txt \
     /tmp/

## TODO: Ensure build isolation
RUN pip install --no-cache-dir -r /tmp/requirements.txt
RUN pip install --index-url https://pypi.org/simple --no-cache-dir -r /tmp/requirements-pypi.txt
